/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.serve.resource.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.serve.resource.model.Continent;
import com.liferay.serve.resource.model.ContinentModel;
import com.liferay.serve.resource.model.ContinentSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Continent service. Represents a row in the &quot;FOO_Continent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContinentModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContinentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContinentImpl
 * @generated
 */
@JSON(strict = true)
public class ContinentModelImpl
	extends BaseModelImpl<Continent> implements ContinentModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a continent model instance should use the <code>Continent</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_Continent";

	public static final Object[][] TABLE_COLUMNS = {
		{"continentCode", Types.VARCHAR}, {"continentName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("continentCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("continentName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_Continent (continentCode VARCHAR(75) not null primary key,continentName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_Continent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY continent.continentCode ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_Continent.continentCode ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTINENTCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Continent toModel(ContinentSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Continent model = new ContinentImpl();

		model.setContinentCode(soapModel.getContinentCode());
		model.setContinentName(soapModel.getContinentName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Continent> toModels(ContinentSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Continent> models = new ArrayList<Continent>(soapModels.length);

		for (ContinentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ContinentModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _continentCode;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setContinentCode(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _continentCode;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Continent.class;
	}

	@Override
	public String getModelClassName() {
		return Continent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Continent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Continent, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Continent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Continent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Continent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Continent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Continent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Continent.class.getClassLoader(), Continent.class,
			ModelWrapper.class);

		try {
			Constructor<Continent> constructor =
				(Constructor<Continent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Continent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Continent, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Continent, Object>>();
		Map<String, BiConsumer<Continent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Continent, ?>>();

		attributeGetterFunctions.put(
			"continentCode", Continent::getContinentCode);
		attributeSetterBiConsumers.put(
			"continentCode",
			(BiConsumer<Continent, String>)Continent::setContinentCode);
		attributeGetterFunctions.put(
			"continentName", Continent::getContinentName);
		attributeSetterBiConsumers.put(
			"continentName",
			(BiConsumer<Continent, String>)Continent::setContinentName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getContinentCode() {
		if (_continentCode == null) {
			return "";
		}
		else {
			return _continentCode;
		}
	}

	@Override
	public void setContinentCode(String continentCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_continentCode = continentCode;
	}

	@JSON
	@Override
	public String getContinentName() {
		if (_continentName == null) {
			return "";
		}
		else {
			return _continentName;
		}
	}

	@Override
	public void setContinentName(String continentName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_continentName = continentName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Continent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Continent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContinentImpl continentImpl = new ContinentImpl();

		continentImpl.setContinentCode(getContinentCode());
		continentImpl.setContinentName(getContinentName());

		continentImpl.resetOriginalValues();

		return continentImpl;
	}

	@Override
	public int compareTo(Continent continent) {
		String primaryKey = continent.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Continent)) {
			return false;
		}

		Continent continent = (Continent)object;

		String primaryKey = continent.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Continent> toCacheModel() {
		ContinentCacheModel continentCacheModel = new ContinentCacheModel();

		continentCacheModel.continentCode = getContinentCode();

		String continentCode = continentCacheModel.continentCode;

		if ((continentCode != null) && (continentCode.length() == 0)) {
			continentCacheModel.continentCode = null;
		}

		continentCacheModel.continentName = getContinentName();

		String continentName = continentCacheModel.continentName;

		if ((continentName != null) && (continentName.length() == 0)) {
			continentCacheModel.continentName = null;
		}

		return continentCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Continent)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Continent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Continent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Continent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Continent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Continent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _continentCode;
	private String _continentName;

	public <T> T getColumnValue(String columnName) {
		Function<Continent, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Continent)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("continentCode", _continentCode);
		_columnOriginalValues.put("continentName", _continentName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("continentCode", 1L);

		columnBitmasks.put("continentName", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Continent _escapedModel;

}