/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.serve.resource.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.serve.resource.model.States;
import com.liferay.serve.resource.model.StatesModel;
import com.liferay.serve.resource.model.StatesSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the States service. Represents a row in the &quot;FOO_States&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>StatesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatesImpl
 * @generated
 */
@JSON(strict = true)
public class StatesModelImpl
	extends BaseModelImpl<States> implements StatesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a states model instance should use the <code>States</code> interface instead.
	 */
	public static final String TABLE_NAME = "FOO_States";

	public static final Object[][] TABLE_COLUMNS = {
		{"stateAbbrev", Types.VARCHAR}, {"stateName", Types.VARCHAR},
		{"countryCode", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("stateAbbrev", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("countryCode", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table FOO_States (stateAbbrev VARCHAR(75) not null primary key,stateName VARCHAR(75) null,countryCode VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table FOO_States";

	public static final String ORDER_BY_JPQL =
		" ORDER BY states.stateAbbrev ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY FOO_States.stateAbbrev ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COUNTRYCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATEABBREV_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static States toModel(StatesSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		States model = new StatesImpl();

		model.setStateAbbrev(soapModel.getStateAbbrev());
		model.setStateName(soapModel.getStateName());
		model.setCountryCode(soapModel.getCountryCode());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<States> toModels(StatesSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<States> models = new ArrayList<States>(soapModels.length);

		for (StatesSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public StatesModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _stateAbbrev;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setStateAbbrev(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stateAbbrev;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return States.class;
	}

	@Override
	public String getModelClassName() {
		return States.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<States, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<States, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<States, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((States)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<States, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<States, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(States)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<States, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<States, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, States>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			States.class.getClassLoader(), States.class, ModelWrapper.class);

		try {
			Constructor<States> constructor =
				(Constructor<States>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<States, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<States, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<States, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<States, Object>>();
		Map<String, BiConsumer<States, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<States, ?>>();

		attributeGetterFunctions.put("stateAbbrev", States::getStateAbbrev);
		attributeSetterBiConsumers.put(
			"stateAbbrev", (BiConsumer<States, String>)States::setStateAbbrev);
		attributeGetterFunctions.put("stateName", States::getStateName);
		attributeSetterBiConsumers.put(
			"stateName", (BiConsumer<States, String>)States::setStateName);
		attributeGetterFunctions.put("countryCode", States::getCountryCode);
		attributeSetterBiConsumers.put(
			"countryCode", (BiConsumer<States, String>)States::setCountryCode);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getStateAbbrev() {
		if (_stateAbbrev == null) {
			return "";
		}
		else {
			return _stateAbbrev;
		}
	}

	@Override
	public void setStateAbbrev(String stateAbbrev) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateAbbrev = stateAbbrev;
	}

	@JSON
	@Override
	public String getStateName() {
		if (_stateName == null) {
			return "";
		}
		else {
			return _stateName;
		}
	}

	@Override
	public void setStateName(String stateName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateName = stateName;
	}

	@JSON
	@Override
	public String getCountryCode() {
		if (_countryCode == null) {
			return "";
		}
		else {
			return _countryCode;
		}
	}

	@Override
	public void setCountryCode(String countryCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_countryCode = countryCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCountryCode() {
		return getColumnOriginalValue("countryCode");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public States toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, States>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatesImpl statesImpl = new StatesImpl();

		statesImpl.setStateAbbrev(getStateAbbrev());
		statesImpl.setStateName(getStateName());
		statesImpl.setCountryCode(getCountryCode());

		statesImpl.resetOriginalValues();

		return statesImpl;
	}

	@Override
	public int compareTo(States states) {
		String primaryKey = states.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof States)) {
			return false;
		}

		States states = (States)object;

		String primaryKey = states.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<States> toCacheModel() {
		StatesCacheModel statesCacheModel = new StatesCacheModel();

		statesCacheModel.stateAbbrev = getStateAbbrev();

		String stateAbbrev = statesCacheModel.stateAbbrev;

		if ((stateAbbrev != null) && (stateAbbrev.length() == 0)) {
			statesCacheModel.stateAbbrev = null;
		}

		statesCacheModel.stateName = getStateName();

		String stateName = statesCacheModel.stateName;

		if ((stateName != null) && (stateName.length() == 0)) {
			statesCacheModel.stateName = null;
		}

		statesCacheModel.countryCode = getCountryCode();

		String countryCode = statesCacheModel.countryCode;

		if ((countryCode != null) && (countryCode.length() == 0)) {
			statesCacheModel.countryCode = null;
		}

		return statesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<States, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<States, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<States, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((States)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<States, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<States, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<States, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((States)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, States>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _stateAbbrev;
	private String _stateName;
	private String _countryCode;

	public <T> T getColumnValue(String columnName) {
		Function<States, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((States)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("stateAbbrev", _stateAbbrev);
		_columnOriginalValues.put("stateName", _stateName);
		_columnOriginalValues.put("countryCode", _countryCode);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("stateAbbrev", 1L);

		columnBitmasks.put("stateName", 2L);

		columnBitmasks.put("countryCode", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private States _escapedModel;

}